apps/tiger/urls.py
from django.conf.urls.defaults import patterns, include, url
from .views import manage_cards, receive_webhook, edit_card, delete_card,make_default_card

urlpatterns = patterns('',
    url(r'^manage/$', manage_cards, name='tiger_manage_cards'),
    url(r'^add_card/$', edit_card, name='tiger_add_card'),
    url(r'^delete_card/(?P<card_id>\d+)/$', delete_card, name='tiger_delete_card'),
    url(r'^make_default/(?P<card_id>\d+)/$', make_default_card, name='tiger_make_default_card'),
    url(r'^receive_webhook/$', receive_webhook, name='tiger_receive_webhook')
)

apps/tiger/forms.py
import re
import datetime

from django.forms.widgets import Widget, Select
from django import forms
from django.utils.dates import MONTHS
from django.contrib.localflavor.us.forms import USStateField, USZipCodeField
from django.utils.encoding import force_unicode
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.forms.util import flatatt


class PCISafeTextInput(forms.TextInput):
    def render(self, name, value, attrs=None):
        """
        Don't include the name in the rendered HTML, so
        value never gets POSTed to the server.
        """
        if value is None:
            value = ''
        final_attrs = self.build_attrs(attrs, type=self.input_type)
        if value is not None:
            final_attrs['value'] = force_unicode(self._format_value(value))
            final_attrs['autocomplete'] = 'off'
        return mark_safe('<input%s />' % flatatt(final_attrs))


class PCISafeCharField(forms.CharField):
    widget = PCISafeTextInput

    def clean(self, *args, **kwargs):
        return ""


CARD_CHOICES = {
    ('Visa', 'Visa'),
    ('American Express', 'American Express'),
    ('MasterCard', 'MasterCard'),
    ('Discover', 'Discover'),
    ('JCB', 'JCB'),
    ('Diners Club', 'Diners Club')
}


# class CreditCardForm(forms.Form):
#     """
#     Form that renders all widgets, but only expects a 'stripe_token' in the
#     POSTed response, for easy PCI compliance.

#     Note that no server side field validation is performed.
#     """
#     cc_type = forms.ChoiceField(choices=CARD_CHOICES, label="Card type")
#     cc_number = PCISafeCharField(label="Card number")
#     ccv = PCISafeCharField(max_length=4, label="CCV")
#     name = forms.CharField(max_length=200)
#     address_line_1 = forms.CharField(max_length=200)
#     address_line_2 = forms.CharField(max_length=200, required=False)
#     city = forms.CharField(max_length=200)
#     state = USStateField()
#     zipcode = USZipCodeField()
#     stripe_token = forms.CharField(widget=forms.HiddenInput)


RE_DATE = re.compile(r'(\d{4})-(\d\d?)-(\d\d?)$')


class MonthYearWidget(Widget):
    """
    A Widget that splits date input into two <select> boxes for month and year,
    with 'day' defaulting to the first of the month.

    Based on SelectDateWidget, in

    django/trunk/django/forms/extras/widgets.py


    """
    none_value = (0, '---')
    month_field = '%s_month'
    year_field = '%s_year'

    def __init__(self, attrs=None, years=None, required=True):
        # years is an optional list/tuple of years to use in the "year"
        # select box.
        self.attrs = attrs or {}
        self.required = required
        if years:
            self.years = years
        else:
            this_year = datetime.date.today().year
            self.years = range(this_year, this_year + 10)

    def render(self, name, value, attrs=None):
        try:
            year_val, month_val = value.year, value.month
        except AttributeError:
            year_val = month_val = None
            if isinstance(value, basestring):
                match = RE_DATE.match(value)
                if match:
                    year_val, month_val, day_val = [int(v)
                                                    for v in match.groups()]

        output = []

        if 'id' in self.attrs:
            id_ = self.attrs['id']
        else:
            id_ = 'id_%s' % name

        month_choices = MONTHS.items()
        if not (self.required and value):
            month_choices.append(self.none_value)
        month_choices.sort()
        local_attrs = self.build_attrs(id=self.month_field % id_)
        s = Select(choices=month_choices)
        select_html = s.render(self.month_field % name, month_val, local_attrs)
        output.append(select_html)

        year_choices = [(i, i) for i in self.years]
        if not (self.required and value):
            year_choices.insert(0, self.none_value)
        local_attrs['id'] = self.year_field % id_
        s = Select(choices=year_choices)
        select_html = s.render(self.year_field % name, year_val, local_attrs)
        output.append(select_html)

        return mark_safe(u'\n'.join(output))

    def id_for_label(self, id_):
        return '%s_month' % id_
    id_for_label = classmethod(id_for_label)

    def value_from_datadict(self, data, files, name):
        y = data.get(self.year_field % name)
        m = data.get(self.month_field % name)
        if y == m == "0":
            return None
        if y and m:
            return '%s-%s-%s' % (y, m, 1)
        return data.get(name, None)


class CreditCardForm(forms.Form):
    """
    Form that renders all widgets, but only expects a 'stripe_token' in the
    POSTed response, for easy PCI compliance.

    Note that no server side field validation is performed.
    """
    card_type = forms.ChoiceField(choices=CARD_CHOICES, label=_('Card Type'))
    card_number = PCISafeCharField(label=_('Card Number'))
    expiration_date = forms.CharField(widget=MonthYearWidget(), label=_('Expiration Date'))
    verification_number = PCISafeCharField(max_length=4, label=_('Verification Number'),
                                           help_text="Last 3 digits on the back of your card. For AmEx, 4 digits on the first")
    card_name = forms.CharField(max_length=200, label=_('Name on Card'))
    billing_address = forms.CharField(max_length=200, label=_('Address'))
    billing_address_2 = forms.CharField(max_length=200, required=False, label=_('Address (line 2)'))
    city = forms.CharField(max_length=50, label=_('City'))
    state = USStateField(label=_('State'))
    zip = USZipCodeField(label=_('Zip'))
    stripe_token = forms.CharField(widget=forms.HiddenInput())

templates/credit_card/add_card.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load stripe %}

{% block content %}
    <div class='container'>
        <div class="row">
            <div class='span5'>
                <h1>Add a Credit Card</h1>
                <form id="edit_card_form" action="" method='post'>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class='btn btn-success' type='submit'>Add Card</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
    $(function(){
        // map stripe error with our form
        var mapping = {'number': 'id_card_number', 'exp_month': 'id_expiration_date_year',
         'exp_year': 'id_expiration_date_year', 'cvc': 'id_verification_number'}
                
        function hide_form_errors(){
            $('.errorlist').remove();
        }
        
        function display_error(field, error_text, is_checkbox){
            if(is_checkbox){
                if (field.find('.help-inline').length > 0){
                    field.parent().siblings('.help-inline').text(error_text);
                }else{
                    // insert help-inline to this field
                    $span = $('<span/>', {'class': 'help-inline'});
                    $span.html(error_text);
                    if(field.next('.chzn-container').length > 0){
                       field.next('.chzn-container').after($span) ;
                    }else{
                        field.after($span);
                    }                    
                }
            }else{
                if (field.find('.help-inline').length > 0){
                    field.siblings('.help-inline').text(error_text);
                }else{
                    // insert help-inline to this field
                    $span = $('<span/>', {'class': 'help-inline'});
                    $span.html(error_text);
                    if(field.next('.chzn-container').length > 0){
                       field.next('.chzn-container').after($span) ;
                    }else{
                        field.after($span);
                    }  
                }
            }
        }
        
        function process_form_errors(json, form){
            var curField;
            hide_form_errors();
            errors = json.errors;
            $("button[type=submit]").removeAttr('disabled');
            
            prefix = form.find(":hidden[name='prefix']").val();
            
            prefix == undefined ? prefix = '' : prefix = prefix + '-';
            $('.error').removeClass('error');
            $('.help-inline').text('');
            
            if (errors.__all__ != undefined){
                // form.append(errors.__all__);
                // append error for email or password based on return value
                
                if (errors.__all__.indexOf('password') !== -1){
                    field = $('[name=password2]');
                }else{
                    field = $('[name=email_again]');
                }
                
                display_error(field, errors.__all__, false);
                field.parents('.control-group:first').addClass('error')
            }
            
            for (field in errors) {
                if(errors.hasOwnProperty(field)){
                    curField = $('[name=' + field + '], [name=' + field + ']');
                    if(curField.attr('type') === 'checkbox'){
                        display_error(curField, errors[field], true);
                    } else {
                        display_error(curField, errors[field], false);
                    }
                    curField.parents('.control-group:first').addClass('error')
                }
            }
        }
        
        function removeErrorForStripe(){
            $('.error').each(function(){
                $(this).find('.help-inline').remove();
                $(this).removeClass('error');
            })
        }
        
        function addErrorForStripe(element, message){
            removeErrorForStripe();
            $span = $('<span/>', {'class': 'help-inline'});
            $span.html(message);
            
            element.after($span);
            element.parents('.control-group:first').addClass('error');
        }
        
        function stripeResponseHandler(status, response) {
            //response:
            //{
            //  id : "tok_u5dg20Gra", // String of token identifier,
            //  card : {...}, // Dictionary of the card used to create the token
            //  created : 1357740841, // Integer of date token was created
            //  currency: "usd", // String currency that the token was created in
            //  livemode: true, // Boolean of whether this token was created with a live or test API key
            //  object: "token", // String identifier of the type of object, always "token"
            //  used : false, // Boolean of whether this token has been used,
            //}
            if (response.error) {
                $('html body').css('cursor', 'auto');
                // console.log(response.error.message);
                $("button[type=submit]").removeAttr('disabled');
                addErrorForStripe($('#' + mapping[response.error.param]), response.error.message);
            }
            else {
                // add the stripe token and submit the form
                var form = $("#edit_card_form");
                $("#id_stripe_token").val(response.id);
                var data = form.serialize();
                $.ajax({
                    url: form.attr('action'),
                    data: data,
                    type: 'post',
                    success: function(json){
                        $('html body').css('cursor', 'auto');
                        if (json.success === false && json.errors !== undefined)
                            process_form_errors(json, form);
                        else {
                            // redirect to manage cards page
                            window.location.href = '{% tiger_manage_cards %}';
                        }
                    }
                });
            }
        }
        
        $('#edit_card_form').submit(function(e){
            e.preventDefault();
            $("button[type=submit]").attr('disabled', 'disabled');
            $('html body').css('cursor', 'wait');
            
            var data = {
                number: $("#id_card_number").val(),
                cvc: $("#id_verification_number").val(),
                exp_month: $("#id_expiration_date_month").val(),
                exp_year: $("#id_expiration_date_year").val()
            };
            Stripe.createToken(data, stripeResponseHandler);
        });
        Stripe.setPublishableKey('{% stripe_pub_key %}');
        
    })
</script>
{% endblock %}

templates/credit_card/cards.html
{% extends "base.html" %}

{% block content %}
    <div class='container'>
        <div class="row">
            <div class="span12">
                <h1>Manage Credit Cards</h1>
                <ul class="unstyled">
                    {% for card in user_cards %}
                        <li>{{ card }}</li>
                    {% empty %}
                        <li>No cards on file.</li>
                    {% endfor %}
                </ul>
                <p><a href="{% url 'tiger_add_card' %}" class='btn btn-success'>Add a card</a></p>
            </div>
        </div>
    </div>
{% endblock content %}